### ISSUE TITLE
Create a new component in the `/components/ui` directory named `ToolSelectionPanel`.

### ISSUE THREAD

**Issue by hbrooks** [nyvyn/codewinder#24]
Summary:
Create a new directory here https://github.com/nyvyn/codewinder/tree/main/components/ui named ToolSelectionPanel. Then create a new Panel component named ToolSelectionPanel that allows the user to select one or more named tools.

Details:
The ToolSelectionPanel component should provide a user-friendly interface for selecting tools from a predefined list. Each tool should have a name associated with it, and the user should be able to select one or more tools.

The component should include the following features:

Display a list of tools with checkboxes or toggle buttons.
Allow the user to select multiple tools at once.
Provide a clear indication of the selected tools.
Emit an event or callback when the selection changes, providing the updated list of selected tools.
Allow customization of the appearance and behavior of the component through props or options.
Ensure the component is accessible and responsive.

Reference these files as an example:
https://github.com/nyvyn/codewinder/blob/main/components/ui/MessageList/index.ts
https://github.com/nyvyn/codewinder/blob/main/components/ui/MessageList/index.ts

Here's a sample skeleton module.
```
import React from 'react';
import ToolSelectionPanel from 'components/ToolSelectionPanel';

function MyComponent() {
const handleToolSelectionChange = (selectedTools) => {
console.log('Selected tools:', selectedTools);
// Handle the selected tools here
};

return (


My Component


<ToolSelectionPanel
tools={['Tool A', 'Tool B', 'Tool C', 'Tool D']}
onChange={handleToolSelectionChange}
/>

);
}
```

```
import React from 'react';
import ToolSelectionPanel from 'components/ToolSelectionPanel';

function MyComponent() {
  const handleToolSelectionChange = (selectedTools) => {
    console.log('Selected tools:', selectedTools);
    // Handle the selected tools here
  };

  return (
    <div>
      <h1>My Component</h1>
      <ToolSelectionPanel
        tools={['Tool A', 'Tool B', 'Tool C', 'Tool D']}
        onChange={handleToolSelectionChange}
      />
    </div>
  );
}
```
_Originally posted by @nyvyn in https://github.com/nyvyn/codewinder/issues/23#issuecomment-1593873211_

**Comment by hbrooks** [comment]
@nyvyn Ready for you to add the label and kick off the code generation process.

The reason your comments weren't working in https://github.com/nyvyn/codewinder/issues/23 is because BitBuilder only looks for details in the issue body, not the comments.  The issue body didn't reference any files.  This one does.

**Comment by nyvyn** [comment]
LGTM

**Comment by hbrooks** [comment]
lgtm

@nyvyn whoops, forgot I have to be the one to approve the plan because I created the issue.  Thanks for raising this bud, will fix
